{
 "title": "RPS Feature Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/rockpaperscissors/start\"}[5m])) by(uri)",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/rockpaperscissors/join\"}[5m])) by(uri)",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/rockpaperscissors/play\"}[5m])) by(uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Registered Players",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "registered_players_total", "legendFormat": "players" }
   ]
  },
  {
   "title": "Registered Players Rate by instance for the last 15 minutes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(started_sessions_total[5m])) by(instance)",
     "legendFormat": "Rate of change for every 5 minutes"
    },
    {
     "expr": "sum(irate(started_sessions_total[5m])) by(instance)",
     "legendFormat": "Rate of change for last 2 datapoints"
    }
   ]
  },
  {
   "title": "Started Sessions Total Rate Last 5 minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(started_sessions_total[5m])",
     "legendFormat": "sessions"
    }
   ]
  },
  {
   "title": "Started Sessions Total (RAW)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "started_sessions_total", "legendFormat": "sessions" }
   ]
  }
 ]
}