spring:
  application:
    name: rock-paper-scissors-2

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PWD:password123}
    hikari:
      connection-timeout: 30000
      idleTimeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20

  jmx:
    enabled: false

server:
  port: 8080

management:
  server:
    port: 8091
    base-path: "/"

  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
    jmx:
      exposure:
        exclude: "*"

  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
    env:
      enabled: true

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"