spring:
  application:
    name: rock-paper-scissors-2

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PWD:password123}

  jmx:
    enabled: false

server:
  port: 8080

management:
  server:
    servlet:
      context-path: "/"
    port: 8091

  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
    jmx:
      exposure:
        exclude: "*"

  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
    env:
      enabled: true
