version: '3'
services:
  postgres:
    image: postgres:11.2
    volumes:
      - ./createTables.sql:/docker-entrypoint-initdb.d/createTables.sql
      - ./postgresql.conf:/etc/postgresql.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - '5432:5432'