###
PUT http://localhost:8080/rockpaperscissors/player/raghava1
###
PUT http://localhost:8080/rockpaperscissors/player/raghava2
###
PUT http://localhost:8080/rockpaperscissors/player/raghava1
###
PUT http://localhost:8080/rockpaperscissors/player/raghava2
###
PUT http://localhost:8080/rockpaperscissors/player/raghava3
###
PUT http://localhost:8080/rockpaperscissors/player/raghava4
###
PUT http://localhost:8080/rockpaperscissors/player/raghava5
###
PUT http://localhost:8080/rockpaperscissors/player/raghava6
###
PUT http://localhost:8080/rockpaperscissors/player/raghava7
###
PUT http://localhost:8080/rockpaperscissors/player/raghava8
###
PUT http://localhost:8080/rockpaperscissors/player/raghava9
###
PUT http://localhost:8080/rockpaperscissors/player/raghava10
###
PUT http://localhost:8080/rockpaperscissors/player/raghava11
###
PUT http://localhost:8080/rockpaperscissors/player/raghava12
###
PUT http://localhost:8080/rockpaperscissors/player/raghava13
###
PUT http://localhost:8080/rockpaperscissors/player/raghava14
###
PUT http://localhost:8080/rockpaperscissors/player/raghava15
###
PUT http://localhost:8080/rockpaperscissors/player/raghava16
###
PUT http://localhost:8080/rockpaperscissors/player/raghava17
###
PUT http://localhost:8080/rockpaperscissors/player/raghava18
###
PUT http://localhost:8080/rockpaperscissors/player/raghava19
###
PUT http://localhost:8080/rockpaperscissors/player/raghava20
###
PUT http://localhost:8080/rockpaperscissors/player/raghava21
###
PUT http://localhost:8080/rockpaperscissors/player/raghava22
###
PUT http://localhost:8080/rockpaperscissors/player/raghava23
###
PUT http://localhost:8080/rockpaperscissors/player/raghava24
###
PUT http://localhost:8080/rockpaperscissors/player/raghava25
###
PUT http://localhost:8080/rockpaperscissors/player/raghava26
###
PUT http://localhost:8080/rockpaperscissors/player/raghava27
###
PUT http://localhost:8080/rockpaperscissors/player/raghava28
###
PUT http://localhost:8080/rockpaperscissors/player/raghava29
###
PUT http://localhost:8080/rockpaperscissors/player/raghava30
###
PUT http://localhost:8080/rockpaperscissors/player/raghava31
###
PUT http://localhost:8080/rockpaperscissors/player/raghava32
###
PUT http://localhost:8080/rockpaperscissors/player/raghava33
###
PUT http://localhost:8080/rockpaperscissors/player/raghava34
###
PUT http://localhost:8080/rockpaperscissors/player/raghava35
###
PUT http://localhost:8080/rockpaperscissors/player/raghava36
###
PUT http://localhost:8080/rockpaperscissors/player/raghava37
###
PUT http://localhost:8080/rockpaperscissors/player/raghava38
###
PUT http://localhost:8080/rockpaperscissors/player/raghava39
###
PUT http://localhost:8080/rockpaperscissors/player/raghava40
###
PUT http://localhost:8080/rockpaperscissors/player/raghava41
###
PUT http://localhost:8080/rockpaperscissors/player/raghava42
###
PUT http://localhost:8080/rockpaperscissors/player/raghava43
###
PUT http://localhost:8080/rockpaperscissors/player/raghava44
###
PUT http://localhost:8080/rockpaperscissors/player/raghava45
###
PUT http://localhost:8080/rockpaperscissors/player/raghava46
###
PUT http://localhost:8080/rockpaperscissors/player/raghava47
###
PUT http://localhost:8080/rockpaperscissors/player/raghava48
###
PUT http://localhost:8080/rockpaperscissors/player/raghava49
###
PUT http://localhost:8080/rockpaperscissors/player/raghava50
###
PUT http://localhost:8080/rockpaperscissors/player/raghava51
###
PUT http://localhost:8080/rockpaperscissors/player/raghava52
###
PUT http://localhost:8080/rockpaperscissors/player/raghava53
###
PUT http://localhost:8080/rockpaperscissors/player/raghava54
###
PUT http://localhost:8080/rockpaperscissors/player/raghava55
###
PUT http://localhost:8080/rockpaperscissors/player/raghava56
###
PUT http://localhost:8080/rockpaperscissors/player/raghava57
###
PUT http://localhost:8080/rockpaperscissors/player/raghava58
###
PUT http://localhost:8080/rockpaperscissors/player/raghava59
###
PUT http://localhost:8080/rockpaperscissors/player/raghava60
###
PUT http://localhost:8080/rockpaperscissors/player/raghava61
###
PUT http://localhost:8080/rockpaperscissors/player/raghava62
###
PUT http://localhost:8080/rockpaperscissors/player/raghava63
###
PUT http://localhost:8080/rockpaperscissors/player/raghava64
###
PUT http://localhost:8080/rockpaperscissors/player/raghava65
###
PUT http://localhost:8080/rockpaperscissors/player/raghava66
###
PUT http://localhost:8080/rockpaperscissors/player/raghava67
###
PUT http://localhost:8080/rockpaperscissors/player/raghava68
###
PUT http://localhost:8080/rockpaperscissors/player/raghava69
###
PUT http://localhost:8080/rockpaperscissors/player/raghava70
###
PUT http://localhost:8080/rockpaperscissors/player/raghava71
###
PUT http://localhost:8080/rockpaperscissors/player/raghava72
###
PUT http://localhost:8080/rockpaperscissors/player/raghava73
###
PUT http://localhost:8080/rockpaperscissors/player/raghava74
###
PUT http://localhost:8080/rockpaperscissors/player/raghava75
###
PUT http://localhost:8080/rockpaperscissors/player/raghava76
###
PUT http://localhost:8080/rockpaperscissors/player/raghava77
###
PUT http://localhost:8080/rockpaperscissors/player/raghava78
###
PUT http://localhost:8080/rockpaperscissors/player/raghava79
###
PUT http://localhost:8080/rockpaperscissors/player/raghava80
###
PUT http://localhost:8080/rockpaperscissors/player/raghava81
###
PUT http://localhost:8080/rockpaperscissors/player/raghava82
###
PUT http://localhost:8080/rockpaperscissors/player/raghava83
###
PUT http://localhost:8080/rockpaperscissors/player/raghava84
###
PUT http://localhost:8080/rockpaperscissors/player/raghava85
###
PUT http://localhost:8080/rockpaperscissors/player/raghava86
###
PUT http://localhost:8080/rockpaperscissors/player/raghava87
###
PUT http://localhost:8080/rockpaperscissors/player/raghava88
###
PUT http://localhost:8080/rockpaperscissors/player/raghava89
###
PUT http://localhost:8080/rockpaperscissors/player/raghava90
###
PUT http://localhost:8080/rockpaperscissors/player/raghava91
###
PUT http://localhost:8080/rockpaperscissors/player/raghava92
###
PUT http://localhost:8080/rockpaperscissors/player/raghava93
###
PUT http://localhost:8080/rockpaperscissors/player/raghava94
###
PUT http://localhost:8080/rockpaperscissors/player/raghava95
###
PUT http://localhost:8080/rockpaperscissors/player/raghava96
###
PUT http://localhost:8080/rockpaperscissors/player/raghava97
###
PUT http://localhost:8080/rockpaperscissors/player/raghava98
###
PUT http://localhost:8080/rockpaperscissors/player/raghava99
###
PUT http://localhost:8080/rockpaperscissors/player/raghava100
###
PUT http://localhost:8080/rockpaperscissors/player/raghava101
###
PUT http://localhost:8080/rockpaperscissors/player/raghava102
###
PUT http://localhost:8080/rockpaperscissors/player/raghava103
###
PUT http://localhost:8080/rockpaperscissors/player/raghava104
###
PUT http://localhost:8080/rockpaperscissors/player/raghava105
###
PUT http://localhost:8080/rockpaperscissors/player/raghava106
###
PUT http://localhost:8080/rockpaperscissors/player/raghava107
###
PUT http://localhost:8080/rockpaperscissors/player/raghava108
###
PUT http://localhost:8080/rockpaperscissors/player/raghava109
###
PUT http://localhost:8080/rockpaperscissors/player/raghava110
###
PUT http://localhost:8080/rockpaperscissors/player/raghava111
###
PUT http://localhost:8080/rockpaperscissors/player/raghava112
###
PUT http://localhost:8080/rockpaperscissors/player/raghava113
###
PUT http://localhost:8080/rockpaperscissors/player/raghava114
###
PUT http://localhost:8080/rockpaperscissors/player/raghava115
###
PUT http://localhost:8080/rockpaperscissors/player/raghava116
###
PUT http://localhost:8080/rockpaperscissors/player/raghava117
###
PUT http://localhost:8080/rockpaperscissors/player/raghava118
###
PUT http://localhost:8080/rockpaperscissors/player/raghava119
###
PUT http://localhost:8080/rockpaperscissors/player/raghava120
###
PUT http://localhost:8080/rockpaperscissors/player/raghava121
###
PUT http://localhost:8080/rockpaperscissors/player/raghava122
###
PUT http://localhost:8080/rockpaperscissors/player/raghava123
###
PUT http://localhost:8080/rockpaperscissors/player/raghava124
###
PUT http://localhost:8080/rockpaperscissors/player/raghava125
###
PUT http://localhost:8080/rockpaperscissors/player/raghava126
###
PUT http://localhost:8080/rockpaperscissors/player/raghava127
###
PUT http://localhost:8080/rockpaperscissors/player/raghava128
###
PUT http://localhost:8080/rockpaperscissors/player/raghava129
###
PUT http://localhost:8080/rockpaperscissors/player/raghava130
###
PUT http://localhost:8080/rockpaperscissors/player/raghava131
###
PUT http://localhost:8080/rockpaperscissors/player/raghava132
###
PUT http://localhost:8080/rockpaperscissors/player/raghava133
###
PUT http://localhost:8080/rockpaperscissors/player/raghava134
###
PUT http://localhost:8080/rockpaperscissors/player/raghava135
###
PUT http://localhost:8080/rockpaperscissors/player/raghava136
###
PUT http://localhost:8080/rockpaperscissors/player/raghava137
###
PUT http://localhost:8080/rockpaperscissors/player/raghava138
###
PUT http://localhost:8080/rockpaperscissors/player/raghava139
###
PUT http://localhost:8080/rockpaperscissors/player/raghava140
###
PUT http://localhost:8080/rockpaperscissors/player/raghava141
###
PUT http://localhost:8080/rockpaperscissors/player/raghava142
###
PUT http://localhost:8080/rockpaperscissors/player/raghava143
###
PUT http://localhost:8080/rockpaperscissors/player/raghava144
###
PUT http://localhost:8080/rockpaperscissors/player/raghava145
###
PUT http://localhost:8080/rockpaperscissors/player/raghava146
###
PUT http://localhost:8080/rockpaperscissors/player/raghava147
###
PUT http://localhost:8080/rockpaperscissors/player/raghava148
###
PUT http://localhost:8080/rockpaperscissors/player/raghava149
###
PUT http://localhost:8080/rockpaperscissors/player/raghava150
###
PUT http://localhost:8080/rockpaperscissors/player/raghava151
###
PUT http://localhost:8080/rockpaperscissors/player/raghava152
###
PUT http://localhost:8080/rockpaperscissors/player/raghava153
###
PUT http://localhost:8080/rockpaperscissors/player/raghava154
###
PUT http://localhost:8080/rockpaperscissors/player/raghava155
###
PUT http://localhost:8080/rockpaperscissors/player/raghava156
###
PUT http://localhost:8080/rockpaperscissors/player/raghava157
###
PUT http://localhost:8080/rockpaperscissors/player/raghava158
###
PUT http://localhost:8080/rockpaperscissors/player/raghava159
###
PUT http://localhost:8080/rockpaperscissors/player/raghava160
###
PUT http://localhost:8080/rockpaperscissors/player/raghava161
###
PUT http://localhost:8080/rockpaperscissors/player/raghava162
###
PUT http://localhost:8080/rockpaperscissors/player/raghava163
###
PUT http://localhost:8080/rockpaperscissors/player/raghava164
###
PUT http://localhost:8080/rockpaperscissors/player/raghava165
###
PUT http://localhost:8080/rockpaperscissors/player/raghava166
###
PUT http://localhost:8080/rockpaperscissors/player/raghava167
###
PUT http://localhost:8080/rockpaperscissors/player/raghava168
###
PUT http://localhost:8080/rockpaperscissors/player/raghava169
###
PUT http://localhost:8080/rockpaperscissors/player/raghava170
###
PUT http://localhost:8080/rockpaperscissors/player/raghava171
###
PUT http://localhost:8080/rockpaperscissors/player/raghava172
###
PUT http://localhost:8080/rockpaperscissors/player/raghava173
###
PUT http://localhost:8080/rockpaperscissors/player/raghava174
###
PUT http://localhost:8080/rockpaperscissors/player/raghava175
###
PUT http://localhost:8080/rockpaperscissors/player/raghava176
###
PUT http://localhost:8080/rockpaperscissors/player/raghava177
###
PUT http://localhost:8080/rockpaperscissors/player/raghava178
###
PUT http://localhost:8080/rockpaperscissors/player/raghava179
###
PUT http://localhost:8080/rockpaperscissors/player/raghava180
###
PUT http://localhost:8080/rockpaperscissors/player/raghava181
###
PUT http://localhost:8080/rockpaperscissors/player/raghava182
###
PUT http://localhost:8080/rockpaperscissors/player/raghava183
###
PUT http://localhost:8080/rockpaperscissors/player/raghava184
###
PUT http://localhost:8080/rockpaperscissors/player/raghava185
###
PUT http://localhost:8080/rockpaperscissors/player/raghava186
###
PUT http://localhost:8080/rockpaperscissors/player/raghava187
###
PUT http://localhost:8080/rockpaperscissors/player/raghava188
###
PUT http://localhost:8080/rockpaperscissors/player/raghava189
###
PUT http://localhost:8080/rockpaperscissors/player/raghava190
###
PUT http://localhost:8080/rockpaperscissors/player/raghava191
###
PUT http://localhost:8080/rockpaperscissors/player/raghava192
###
PUT http://localhost:8080/rockpaperscissors/player/raghava193
###
PUT http://localhost:8080/rockpaperscissors/player/raghava194
###
PUT http://localhost:8080/rockpaperscissors/player/raghava195
###
PUT http://localhost:8080/rockpaperscissors/player/raghava196
###
PUT http://localhost:8080/rockpaperscissors/player/raghava197
###
PUT http://localhost:8080/rockpaperscissors/player/raghava198
###
PUT http://localhost:8080/rockpaperscissors/player/raghava199
###
PUT http://localhost:8080/rockpaperscissors/player/raghava200
###
PUT http://localhost:8080/rockpaperscissors/player/raghava201
###
PUT http://localhost:8080/rockpaperscissors/player/raghava202
###
PUT http://localhost:8080/rockpaperscissors/player/raghava203
###
PUT http://localhost:8080/rockpaperscissors/player/raghava204
###
PUT http://localhost:8080/rockpaperscissors/player/raghava205
###
PUT http://localhost:8080/rockpaperscissors/player/raghava206
###
PUT http://localhost:8080/rockpaperscissors/player/raghava207
###
PUT http://localhost:8080/rockpaperscissors/player/raghava208
###
PUT http://localhost:8080/rockpaperscissors/player/raghava209
###
PUT http://localhost:8080/rockpaperscissors/player/raghava210
###
PUT http://localhost:8080/rockpaperscissors/player/raghava211
###
PUT http://localhost:8080/rockpaperscissors/player/raghava212
###
PUT http://localhost:8080/rockpaperscissors/player/raghava213
###
PUT http://localhost:8080/rockpaperscissors/player/raghava214
###
PUT http://localhost:8080/rockpaperscissors/player/raghava215
###
PUT http://localhost:8080/rockpaperscissors/player/raghava216
###
PUT http://localhost:8080/rockpaperscissors/player/raghava217
###
PUT http://localhost:8080/rockpaperscissors/player/raghava218
###
PUT http://localhost:8080/rockpaperscissors/player/raghava219
###
PUT http://localhost:8080/rockpaperscissors/player/raghava220
###
PUT http://localhost:8080/rockpaperscissors/player/raghava221
###
PUT http://localhost:8080/rockpaperscissors/player/raghava222
###
PUT http://localhost:8080/rockpaperscissors/player/raghava223
###
PUT http://localhost:8080/rockpaperscissors/player/raghava224
###
PUT http://localhost:8080/rockpaperscissors/player/raghava225
###
PUT http://localhost:8080/rockpaperscissors/player/raghava226
###
PUT http://localhost:8080/rockpaperscissors/player/raghava227
###
PUT http://localhost:8080/rockpaperscissors/player/raghava228
###
PUT http://localhost:8080/rockpaperscissors/player/raghava229
###
PUT http://localhost:8080/rockpaperscissors/player/raghava230
###
PUT http://localhost:8080/rockpaperscissors/player/raghava231
###
PUT http://localhost:8080/rockpaperscissors/player/raghava232
###
PUT http://localhost:8080/rockpaperscissors/player/raghava233
###
PUT http://localhost:8080/rockpaperscissors/player/raghava234
###
PUT http://localhost:8080/rockpaperscissors/player/raghava235
###
PUT http://localhost:8080/rockpaperscissors/player/raghava236
###
PUT http://localhost:8080/rockpaperscissors/player/raghava237
###
PUT http://localhost:8080/rockpaperscissors/player/raghava238
###
PUT http://localhost:8080/rockpaperscissors/player/raghava239
###
PUT http://localhost:8080/rockpaperscissors/player/raghava240
###
PUT http://localhost:8080/rockpaperscissors/player/raghava241
###
PUT http://localhost:8080/rockpaperscissors/player/raghava242
###
PUT http://localhost:8080/rockpaperscissors/player/raghava243
###
PUT http://localhost:8080/rockpaperscissors/player/raghava244
###
PUT http://localhost:8080/rockpaperscissors/player/raghava245
###
PUT http://localhost:8080/rockpaperscissors/player/raghava246
###
PUT http://localhost:8080/rockpaperscissors/player/raghava247
###
PUT http://localhost:8080/rockpaperscissors/player/raghava248
###
PUT http://localhost:8080/rockpaperscissors/player/raghava249
###
PUT http://localhost:8080/rockpaperscissors/player/raghava250
###
PUT http://localhost:8080/rockpaperscissors/player/raghava251
###
PUT http://localhost:8080/rockpaperscissors/player/raghava252
###
PUT http://localhost:8080/rockpaperscissors/player/raghava253
###
PUT http://localhost:8080/rockpaperscissors/player/raghava254
###
PUT http://localhost:8080/rockpaperscissors/player/raghava255
###
PUT http://localhost:8080/rockpaperscissors/player/raghava256
###
PUT http://localhost:8080/rockpaperscissors/player/raghava257
###
PUT http://localhost:8080/rockpaperscissors/player/raghava258
###
PUT http://localhost:8080/rockpaperscissors/player/raghava259
###
PUT http://localhost:8080/rockpaperscissors/player/raghava260
###
PUT http://localhost:8080/rockpaperscissors/player/raghava261
###
PUT http://localhost:8080/rockpaperscissors/player/raghava262
###
PUT http://localhost:8080/rockpaperscissors/player/raghava263
###
PUT http://localhost:8080/rockpaperscissors/player/raghava264
###
PUT http://localhost:8080/rockpaperscissors/player/raghava265
###
PUT http://localhost:8080/rockpaperscissors/player/raghava266
###
PUT http://localhost:8080/rockpaperscissors/player/raghava267
###
PUT http://localhost:8080/rockpaperscissors/player/raghava268
###
PUT http://localhost:8080/rockpaperscissors/player/raghava269
###
PUT http://localhost:8080/rockpaperscissors/player/raghava270
###
PUT http://localhost:8080/rockpaperscissors/player/raghava271
###
PUT http://localhost:8080/rockpaperscissors/player/raghava272
###
PUT http://localhost:8080/rockpaperscissors/player/raghava273
###
PUT http://localhost:8080/rockpaperscissors/player/raghava274
###
PUT http://localhost:8080/rockpaperscissors/player/raghava275
###
PUT http://localhost:8080/rockpaperscissors/player/raghava276
###
PUT http://localhost:8080/rockpaperscissors/player/raghava277
###
PUT http://localhost:8080/rockpaperscissors/player/raghava278
###
PUT http://localhost:8080/rockpaperscissors/player/raghava279
###
PUT http://localhost:8080/rockpaperscissors/player/raghava280
###
PUT http://localhost:8080/rockpaperscissors/player/raghava281
###
PUT http://localhost:8080/rockpaperscissors/player/raghava282
###
PUT http://localhost:8080/rockpaperscissors/player/raghava283
###
PUT http://localhost:8080/rockpaperscissors/player/raghava284
###
PUT http://localhost:8080/rockpaperscissors/player/raghava285
###
PUT http://localhost:8080/rockpaperscissors/player/raghava286
###
PUT http://localhost:8080/rockpaperscissors/player/raghava287
###
PUT http://localhost:8080/rockpaperscissors/player/raghava288
###
PUT http://localhost:8080/rockpaperscissors/player/raghava289
###
PUT http://localhost:8080/rockpaperscissors/player/raghava290
###
PUT http://localhost:8080/rockpaperscissors/player/raghava291
###
PUT http://localhost:8080/rockpaperscissors/player/raghava292
###
PUT http://localhost:8080/rockpaperscissors/player/raghava293
###
PUT http://localhost:8080/rockpaperscissors/player/raghava294
###
PUT http://localhost:8080/rockpaperscissors/player/raghava295
###
PUT http://localhost:8080/rockpaperscissors/player/raghava296
###
PUT http://localhost:8080/rockpaperscissors/player/raghava297
###
PUT http://localhost:8080/rockpaperscissors/player/raghava298
###
PUT http://localhost:8080/rockpaperscissors/player/raghava299
###
PUT http://localhost:8080/rockpaperscissors/player/raghava300
###
PUT http://localhost:8080/rockpaperscissors/player/raghava301
###
PUT http://localhost:8080/rockpaperscissors/player/raghava302
###
PUT http://localhost:8080/rockpaperscissors/player/raghava303
###
PUT http://localhost:8080/rockpaperscissors/player/raghava304
###
PUT http://localhost:8080/rockpaperscissors/player/raghava305
###
PUT http://localhost:8080/rockpaperscissors/player/raghava306
###
PUT http://localhost:8080/rockpaperscissors/player/raghava307
###
PUT http://localhost:8080/rockpaperscissors/player/raghava308
###
PUT http://localhost:8080/rockpaperscissors/player/raghava309
###
PUT http://localhost:8080/rockpaperscissors/player/raghava310
###
PUT http://localhost:8080/rockpaperscissors/player/raghava311
###
PUT http://localhost:8080/rockpaperscissors/player/raghava312
###
PUT http://localhost:8080/rockpaperscissors/player/raghava313
###
PUT http://localhost:8080/rockpaperscissors/player/raghava314
###
PUT http://localhost:8080/rockpaperscissors/player/raghava315
###
PUT http://localhost:8080/rockpaperscissors/player/raghava316
###
PUT http://localhost:8080/rockpaperscissors/player/raghava317
###
PUT http://localhost:8080/rockpaperscissors/player/raghava318
###
PUT http://localhost:8080/rockpaperscissors/player/raghava319
###
PUT http://localhost:8080/rockpaperscissors/player/raghava320
###
PUT http://localhost:8080/rockpaperscissors/player/raghava321
###
PUT http://localhost:8080/rockpaperscissors/player/raghava322
###
PUT http://localhost:8080/rockpaperscissors/player/raghava323
###
PUT http://localhost:8080/rockpaperscissors/player/raghava324