###
POST http://localhost:8080/rockpaperscissors/player/raghava1
###
POST http://localhost:8080/rockpaperscissors/player/raghava2
###
POST http://localhost:8080/rockpaperscissors/player/raghava1
###
POST http://localhost:8080/rockpaperscissors/player/raghava2
###
POST http://localhost:8080/rockpaperscissors/player/raghava3
###
POST http://localhost:8080/rockpaperscissors/player/raghava4
###
POST http://localhost:8080/rockpaperscissors/player/raghava5
###
POST http://localhost:8080/rockpaperscissors/player/raghava6
###
POST http://localhost:8080/rockpaperscissors/player/raghava7
###
POST http://localhost:8080/rockpaperscissors/player/raghava8
###
POST http://localhost:8080/rockpaperscissors/player/raghava9
###
POST http://localhost:8080/rockpaperscissors/player/raghava10
###
POST http://localhost:8080/rockpaperscissors/player/raghava11
###
POST http://localhost:8080/rockpaperscissors/player/raghava12
###
POST http://localhost:8080/rockpaperscissors/player/raghava13
###
POST http://localhost:8080/rockpaperscissors/player/raghava14
###
POST http://localhost:8080/rockpaperscissors/player/raghava15
###
POST http://localhost:8080/rockpaperscissors/player/raghava16
###
POST http://localhost:8080/rockpaperscissors/player/raghava17
###
POST http://localhost:8080/rockpaperscissors/player/raghava18
###
POST http://localhost:8080/rockpaperscissors/player/raghava19
###
POST http://localhost:8080/rockpaperscissors/player/raghava20
###
POST http://localhost:8080/rockpaperscissors/player/raghava21
###
POST http://localhost:8080/rockpaperscissors/player/raghava22
###
POST http://localhost:8080/rockpaperscissors/player/raghava23
###
POST http://localhost:8080/rockpaperscissors/player/raghava24
###
POST http://localhost:8080/rockpaperscissors/player/raghava25
###
POST http://localhost:8080/rockpaperscissors/player/raghava26
###
POST http://localhost:8080/rockpaperscissors/player/raghava27
###
POST http://localhost:8080/rockpaperscissors/player/raghava28
###
POST http://localhost:8080/rockpaperscissors/player/raghava29
###
POST http://localhost:8080/rockpaperscissors/player/raghava30
###
POST http://localhost:8080/rockpaperscissors/player/raghava31
###
POST http://localhost:8080/rockpaperscissors/player/raghava32
###
POST http://localhost:8080/rockpaperscissors/player/raghava33
###
POST http://localhost:8080/rockpaperscissors/player/raghava34
###
POST http://localhost:8080/rockpaperscissors/player/raghava35
###
POST http://localhost:8080/rockpaperscissors/player/raghava36
###
POST http://localhost:8080/rockpaperscissors/player/raghava37
###
POST http://localhost:8080/rockpaperscissors/player/raghava38
###
POST http://localhost:8080/rockpaperscissors/player/raghava39
###
POST http://localhost:8080/rockpaperscissors/player/raghava40
###
POST http://localhost:8080/rockpaperscissors/player/raghava41
###
POST http://localhost:8080/rockpaperscissors/player/raghava42
###
POST http://localhost:8080/rockpaperscissors/player/raghava43
###
POST http://localhost:8080/rockpaperscissors/player/raghava44
###
POST http://localhost:8080/rockpaperscissors/player/raghava45
###
POST http://localhost:8080/rockpaperscissors/player/raghava46
###
POST http://localhost:8080/rockpaperscissors/player/raghava47
###
POST http://localhost:8080/rockpaperscissors/player/raghava48
###
POST http://localhost:8080/rockpaperscissors/player/raghava49
###
POST http://localhost:8080/rockpaperscissors/player/raghava50
###
POST http://localhost:8080/rockpaperscissors/player/raghava51
###
POST http://localhost:8080/rockpaperscissors/player/raghava52
###
POST http://localhost:8080/rockpaperscissors/player/raghava53
###
POST http://localhost:8080/rockpaperscissors/player/raghava54
###
POST http://localhost:8080/rockpaperscissors/player/raghava55
###
POST http://localhost:8080/rockpaperscissors/player/raghava56
###
POST http://localhost:8080/rockpaperscissors/player/raghava57
###
POST http://localhost:8080/rockpaperscissors/player/raghava58
###
POST http://localhost:8080/rockpaperscissors/player/raghava59
###
POST http://localhost:8080/rockpaperscissors/player/raghava60
###
POST http://localhost:8080/rockpaperscissors/player/raghava61
###
POST http://localhost:8080/rockpaperscissors/player/raghava62
###
POST http://localhost:8080/rockpaperscissors/player/raghava63
###
POST http://localhost:8080/rockpaperscissors/player/raghava64
###
POST http://localhost:8080/rockpaperscissors/player/raghava65
###
POST http://localhost:8080/rockpaperscissors/player/raghava66
###
POST http://localhost:8080/rockpaperscissors/player/raghava67
###
POST http://localhost:8080/rockpaperscissors/player/raghava68
###
POST http://localhost:8080/rockpaperscissors/player/raghava69
###
POST http://localhost:8080/rockpaperscissors/player/raghava70
###
POST http://localhost:8080/rockpaperscissors/player/raghava71
###
POST http://localhost:8080/rockpaperscissors/player/raghava72
###
POST http://localhost:8080/rockpaperscissors/player/raghava73
###
POST http://localhost:8080/rockpaperscissors/player/raghava74
###
POST http://localhost:8080/rockpaperscissors/player/raghava75
###
POST http://localhost:8080/rockpaperscissors/player/raghava76
###
POST http://localhost:8080/rockpaperscissors/player/raghava77
###
POST http://localhost:8080/rockpaperscissors/player/raghava78
###
POST http://localhost:8080/rockpaperscissors/player/raghava79
###
POST http://localhost:8080/rockpaperscissors/player/raghava80
###
POST http://localhost:8080/rockpaperscissors/player/raghava81
###
POST http://localhost:8080/rockpaperscissors/player/raghava82
###
POST http://localhost:8080/rockpaperscissors/player/raghava83
###
POST http://localhost:8080/rockpaperscissors/player/raghava84
###
POST http://localhost:8080/rockpaperscissors/player/raghava85
###
POST http://localhost:8080/rockpaperscissors/player/raghava86
###
POST http://localhost:8080/rockpaperscissors/player/raghava87
###
POST http://localhost:8080/rockpaperscissors/player/raghava88
###
POST http://localhost:8080/rockpaperscissors/player/raghava89
###
POST http://localhost:8080/rockpaperscissors/player/raghava90
###
POST http://localhost:8080/rockpaperscissors/player/raghava91
###
POST http://localhost:8080/rockpaperscissors/player/raghava92
###
POST http://localhost:8080/rockpaperscissors/player/raghava93
###
POST http://localhost:8080/rockpaperscissors/player/raghava94
###
POST http://localhost:8080/rockpaperscissors/player/raghava95
###
POST http://localhost:8080/rockpaperscissors/player/raghava96
###
POST http://localhost:8080/rockpaperscissors/player/raghava97
###
POST http://localhost:8080/rockpaperscissors/player/raghava98
###
POST http://localhost:8080/rockpaperscissors/player/raghava99
###
POST http://localhost:8080/rockpaperscissors/player/raghava100
###
POST http://localhost:8080/rockpaperscissors/player/raghava101
###
POST http://localhost:8080/rockpaperscissors/player/raghava102
###
POST http://localhost:8080/rockpaperscissors/player/raghava103
###
POST http://localhost:8080/rockpaperscissors/player/raghava104
###
POST http://localhost:8080/rockpaperscissors/player/raghava105
###
POST http://localhost:8080/rockpaperscissors/player/raghava106
###
POST http://localhost:8080/rockpaperscissors/player/raghava107
###
POST http://localhost:8080/rockpaperscissors/player/raghava108
###
POST http://localhost:8080/rockpaperscissors/player/raghava109
###
POST http://localhost:8080/rockpaperscissors/player/raghava110
###
POST http://localhost:8080/rockpaperscissors/player/raghava111
###
POST http://localhost:8080/rockpaperscissors/player/raghava112
###
POST http://localhost:8080/rockpaperscissors/player/raghava113
###
POST http://localhost:8080/rockpaperscissors/player/raghava114
###
POST http://localhost:8080/rockpaperscissors/player/raghava115
###
POST http://localhost:8080/rockpaperscissors/player/raghava116
###
POST http://localhost:8080/rockpaperscissors/player/raghava117
###
POST http://localhost:8080/rockpaperscissors/player/raghava118
###
POST http://localhost:8080/rockpaperscissors/player/raghava119
###
POST http://localhost:8080/rockpaperscissors/player/raghava120
###
POST http://localhost:8080/rockpaperscissors/player/raghava121
###
POST http://localhost:8080/rockpaperscissors/player/raghava122
###
POST http://localhost:8080/rockpaperscissors/player/raghava123
###
POST http://localhost:8080/rockpaperscissors/player/raghava124
###
POST http://localhost:8080/rockpaperscissors/player/raghava125
###
POST http://localhost:8080/rockpaperscissors/player/raghava126
###
POST http://localhost:8080/rockpaperscissors/player/raghava127
###
POST http://localhost:8080/rockpaperscissors/player/raghava128
###
POST http://localhost:8080/rockpaperscissors/player/raghava129
###
POST http://localhost:8080/rockpaperscissors/player/raghava130
###
POST http://localhost:8080/rockpaperscissors/player/raghava131
###
POST http://localhost:8080/rockpaperscissors/player/raghava132
###
POST http://localhost:8080/rockpaperscissors/player/raghava133
###
POST http://localhost:8080/rockpaperscissors/player/raghava134
###
POST http://localhost:8080/rockpaperscissors/player/raghava135
###
POST http://localhost:8080/rockpaperscissors/player/raghava136
###
POST http://localhost:8080/rockpaperscissors/player/raghava137
###
POST http://localhost:8080/rockpaperscissors/player/raghava138
###
POST http://localhost:8080/rockpaperscissors/player/raghava139
###
POST http://localhost:8080/rockpaperscissors/player/raghava140
###
POST http://localhost:8080/rockpaperscissors/player/raghava141
###
POST http://localhost:8080/rockpaperscissors/player/raghava142
###
POST http://localhost:8080/rockpaperscissors/player/raghava143
###
POST http://localhost:8080/rockpaperscissors/player/raghava144
###
POST http://localhost:8080/rockpaperscissors/player/raghava145
###
POST http://localhost:8080/rockpaperscissors/player/raghava146
###
POST http://localhost:8080/rockpaperscissors/player/raghava147
###
POST http://localhost:8080/rockpaperscissors/player/raghava148
###
POST http://localhost:8080/rockpaperscissors/player/raghava149
###
POST http://localhost:8080/rockpaperscissors/player/raghava150
###
POST http://localhost:8080/rockpaperscissors/player/raghava151
###
POST http://localhost:8080/rockpaperscissors/player/raghava152
###
POST http://localhost:8080/rockpaperscissors/player/raghava153
###
POST http://localhost:8080/rockpaperscissors/player/raghava154
###
POST http://localhost:8080/rockpaperscissors/player/raghava155
###
POST http://localhost:8080/rockpaperscissors/player/raghava156
###
POST http://localhost:8080/rockpaperscissors/player/raghava157
###
POST http://localhost:8080/rockpaperscissors/player/raghava158
###
POST http://localhost:8080/rockpaperscissors/player/raghava159
###
POST http://localhost:8080/rockpaperscissors/player/raghava160
###
POST http://localhost:8080/rockpaperscissors/player/raghava161
###
POST http://localhost:8080/rockpaperscissors/player/raghava162
###
POST http://localhost:8080/rockpaperscissors/player/raghava163
###
POST http://localhost:8080/rockpaperscissors/player/raghava164
###
POST http://localhost:8080/rockpaperscissors/player/raghava165
###
POST http://localhost:8080/rockpaperscissors/player/raghava166
###
POST http://localhost:8080/rockpaperscissors/player/raghava167
###
POST http://localhost:8080/rockpaperscissors/player/raghava168
###
POST http://localhost:8080/rockpaperscissors/player/raghava169
###
POST http://localhost:8080/rockpaperscissors/player/raghava170
###
POST http://localhost:8080/rockpaperscissors/player/raghava171
###
POST http://localhost:8080/rockpaperscissors/player/raghava172
###
POST http://localhost:8080/rockpaperscissors/player/raghava173
###
POST http://localhost:8080/rockpaperscissors/player/raghava174
###
POST http://localhost:8080/rockpaperscissors/player/raghava175
###
POST http://localhost:8080/rockpaperscissors/player/raghava176
###
POST http://localhost:8080/rockpaperscissors/player/raghava177
###
POST http://localhost:8080/rockpaperscissors/player/raghava178
###
POST http://localhost:8080/rockpaperscissors/player/raghava179
###
POST http://localhost:8080/rockpaperscissors/player/raghava180
###
POST http://localhost:8080/rockpaperscissors/player/raghava181
###
POST http://localhost:8080/rockpaperscissors/player/raghava182
###
POST http://localhost:8080/rockpaperscissors/player/raghava183
###
POST http://localhost:8080/rockpaperscissors/player/raghava184
###
POST http://localhost:8080/rockpaperscissors/player/raghava185
###
POST http://localhost:8080/rockpaperscissors/player/raghava186
###
POST http://localhost:8080/rockpaperscissors/player/raghava187
###
POST http://localhost:8080/rockpaperscissors/player/raghava188
###
POST http://localhost:8080/rockpaperscissors/player/raghava189
###
POST http://localhost:8080/rockpaperscissors/player/raghava190
###
POST http://localhost:8080/rockpaperscissors/player/raghava191
###
POST http://localhost:8080/rockpaperscissors/player/raghava192
###
POST http://localhost:8080/rockpaperscissors/player/raghava193
###
POST http://localhost:8080/rockpaperscissors/player/raghava194
###
POST http://localhost:8080/rockpaperscissors/player/raghava195
###
POST http://localhost:8080/rockpaperscissors/player/raghava196
###
POST http://localhost:8080/rockpaperscissors/player/raghava197
###
POST http://localhost:8080/rockpaperscissors/player/raghava198
###
POST http://localhost:8080/rockpaperscissors/player/raghava199
###
POST http://localhost:8080/rockpaperscissors/player/raghava200
###
POST http://localhost:8080/rockpaperscissors/player/raghava201
###
POST http://localhost:8080/rockpaperscissors/player/raghava202
###
POST http://localhost:8080/rockpaperscissors/player/raghava203
###
POST http://localhost:8080/rockpaperscissors/player/raghava204
###
POST http://localhost:8080/rockpaperscissors/player/raghava205
###
POST http://localhost:8080/rockpaperscissors/player/raghava206
###
POST http://localhost:8080/rockpaperscissors/player/raghava207
###
POST http://localhost:8080/rockpaperscissors/player/raghava208
###
POST http://localhost:8080/rockpaperscissors/player/raghava209
###
POST http://localhost:8080/rockpaperscissors/player/raghava210
###
POST http://localhost:8080/rockpaperscissors/player/raghava211
###
POST http://localhost:8080/rockpaperscissors/player/raghava212
###
POST http://localhost:8080/rockpaperscissors/player/raghava213
###
POST http://localhost:8080/rockpaperscissors/player/raghava214
###
POST http://localhost:8080/rockpaperscissors/player/raghava215
###
POST http://localhost:8080/rockpaperscissors/player/raghava216
###
POST http://localhost:8080/rockpaperscissors/player/raghava217
###
POST http://localhost:8080/rockpaperscissors/player/raghava218
###
POST http://localhost:8080/rockpaperscissors/player/raghava219
###
POST http://localhost:8080/rockpaperscissors/player/raghava220
###
POST http://localhost:8080/rockpaperscissors/player/raghava221
###
POST http://localhost:8080/rockpaperscissors/player/raghava222
###
POST http://localhost:8080/rockpaperscissors/player/raghava223
###
POST http://localhost:8080/rockpaperscissors/player/raghava224
###
POST http://localhost:8080/rockpaperscissors/player/raghava225
###
POST http://localhost:8080/rockpaperscissors/player/raghava226
###
POST http://localhost:8080/rockpaperscissors/player/raghava227
###
POST http://localhost:8080/rockpaperscissors/player/raghava228
###
POST http://localhost:8080/rockpaperscissors/player/raghava229
###
POST http://localhost:8080/rockpaperscissors/player/raghava230
###
POST http://localhost:8080/rockpaperscissors/player/raghava231
###
POST http://localhost:8080/rockpaperscissors/player/raghava232
###
POST http://localhost:8080/rockpaperscissors/player/raghava233
###
POST http://localhost:8080/rockpaperscissors/player/raghava234
###
POST http://localhost:8080/rockpaperscissors/player/raghava235
###
POST http://localhost:8080/rockpaperscissors/player/raghava236
###
POST http://localhost:8080/rockpaperscissors/player/raghava237
###
POST http://localhost:8080/rockpaperscissors/player/raghava238
###
POST http://localhost:8080/rockpaperscissors/player/raghava239
###
POST http://localhost:8080/rockpaperscissors/player/raghava240
###
POST http://localhost:8080/rockpaperscissors/player/raghava241
###
POST http://localhost:8080/rockpaperscissors/player/raghava242
###
POST http://localhost:8080/rockpaperscissors/player/raghava243
###
POST http://localhost:8080/rockpaperscissors/player/raghava244
###
POST http://localhost:8080/rockpaperscissors/player/raghava245
###
POST http://localhost:8080/rockpaperscissors/player/raghava246
###
POST http://localhost:8080/rockpaperscissors/player/raghava247
###
POST http://localhost:8080/rockpaperscissors/player/raghava248
###
POST http://localhost:8080/rockpaperscissors/player/raghava249
###
POST http://localhost:8080/rockpaperscissors/player/raghava250
###
POST http://localhost:8080/rockpaperscissors/player/raghava251
###
POST http://localhost:8080/rockpaperscissors/player/raghava252
###
POST http://localhost:8080/rockpaperscissors/player/raghava253
###
POST http://localhost:8080/rockpaperscissors/player/raghava254
###
POST http://localhost:8080/rockpaperscissors/player/raghava255
###
POST http://localhost:8080/rockpaperscissors/player/raghava256
###
POST http://localhost:8080/rockpaperscissors/player/raghava257
###
POST http://localhost:8080/rockpaperscissors/player/raghava258
###
POST http://localhost:8080/rockpaperscissors/player/raghava259
###
POST http://localhost:8080/rockpaperscissors/player/raghava260
###
POST http://localhost:8080/rockpaperscissors/player/raghava261
###
POST http://localhost:8080/rockpaperscissors/player/raghava262
###
POST http://localhost:8080/rockpaperscissors/player/raghava263
###
POST http://localhost:8080/rockpaperscissors/player/raghava264
###
POST http://localhost:8080/rockpaperscissors/player/raghava265
###
POST http://localhost:8080/rockpaperscissors/player/raghava266
###
POST http://localhost:8080/rockpaperscissors/player/raghava267
###
POST http://localhost:8080/rockpaperscissors/player/raghava268
###
POST http://localhost:8080/rockpaperscissors/player/raghava269
###
POST http://localhost:8080/rockpaperscissors/player/raghava270
###
POST http://localhost:8080/rockpaperscissors/player/raghava271
###
POST http://localhost:8080/rockpaperscissors/player/raghava272
###
POST http://localhost:8080/rockpaperscissors/player/raghava273
###
POST http://localhost:8080/rockpaperscissors/player/raghava274
###
POST http://localhost:8080/rockpaperscissors/player/raghava275
###
POST http://localhost:8080/rockpaperscissors/player/raghava276
###
POST http://localhost:8080/rockpaperscissors/player/raghava277
###
POST http://localhost:8080/rockpaperscissors/player/raghava278
###
POST http://localhost:8080/rockpaperscissors/player/raghava279
###
POST http://localhost:8080/rockpaperscissors/player/raghava280
###
POST http://localhost:8080/rockpaperscissors/player/raghava281
###
POST http://localhost:8080/rockpaperscissors/player/raghava282
###
POST http://localhost:8080/rockpaperscissors/player/raghava283
###
POST http://localhost:8080/rockpaperscissors/player/raghava284
###
POST http://localhost:8080/rockpaperscissors/player/raghava285
###
POST http://localhost:8080/rockpaperscissors/player/raghava286
###
POST http://localhost:8080/rockpaperscissors/player/raghava287
###
POST http://localhost:8080/rockpaperscissors/player/raghava288
###
POST http://localhost:8080/rockpaperscissors/player/raghava289
###
POST http://localhost:8080/rockpaperscissors/player/raghava290
###
POST http://localhost:8080/rockpaperscissors/player/raghava291
###
POST http://localhost:8080/rockpaperscissors/player/raghava292
###
POST http://localhost:8080/rockpaperscissors/player/raghava293
###
POST http://localhost:8080/rockpaperscissors/player/raghava294
###
POST http://localhost:8080/rockpaperscissors/player/raghava295
###
POST http://localhost:8080/rockpaperscissors/player/raghava296
###
POST http://localhost:8080/rockpaperscissors/player/raghava297
###
POST http://localhost:8080/rockpaperscissors/player/raghava298
###
POST http://localhost:8080/rockpaperscissors/player/raghava299
###
POST http://localhost:8080/rockpaperscissors/player/raghava300
###
POST http://localhost:8080/rockpaperscissors/player/raghava301
###
POST http://localhost:8080/rockpaperscissors/player/raghava302
###
POST http://localhost:8080/rockpaperscissors/player/raghava303
###
POST http://localhost:8080/rockpaperscissors/player/raghava304
###
POST http://localhost:8080/rockpaperscissors/player/raghava305
###
POST http://localhost:8080/rockpaperscissors/player/raghava306
###
POST http://localhost:8080/rockpaperscissors/player/raghava307
###
POST http://localhost:8080/rockpaperscissors/player/raghava308
###
POST http://localhost:8080/rockpaperscissors/player/raghava309
###
POST http://localhost:8080/rockpaperscissors/player/raghava310
###
POST http://localhost:8080/rockpaperscissors/player/raghava311
###
POST http://localhost:8080/rockpaperscissors/player/raghava312
###
POST http://localhost:8080/rockpaperscissors/player/raghava313
###
POST http://localhost:8080/rockpaperscissors/player/raghava314
###
POST http://localhost:8080/rockpaperscissors/player/raghava315
###
POST http://localhost:8080/rockpaperscissors/player/raghava316
###
POST http://localhost:8080/rockpaperscissors/player/raghava317
###
POST http://localhost:8080/rockpaperscissors/player/raghava318
###
POST http://localhost:8080/rockpaperscissors/player/raghava319
###
POST http://localhost:8080/rockpaperscissors/player/raghava320
###
POST http://localhost:8080/rockpaperscissors/player/raghava321
###
POST http://localhost:8080/rockpaperscissors/player/raghava322
###
POST http://localhost:8080/rockpaperscissors/player/raghava323
###
POST http://localhost:8080/rockpaperscissors/player/raghava324